# frozen_string_literal: true

module ShadcnPhlexcomponents
  class Configuration
    attr_accessor :accordion,
      :alert_dialog,
      :alert,
      :aspect_ratio,
      :avatar,
      :badge,
      :breadcrumb,
      :button,
      :card,
      :checkbox_group,
      :checkbox,
      :combobox,
      :command,
      :date_picker,
      :date_range_picker,
      :dialog,
      :dropdown_menu_sub,
      :dropdown_menu,
      :form,
      :hover_card,
      :input,
      :label,
      :link,
      :pagination,
      :popover,
      :progress,
      :radio_group,
      :select,
      :separator,
      :sheet,
      :skeleton,
      :switch,
      :table,
      :tabs,
      :textarea,
      :theme_switcher,
      :toast_container,
      :toast,
      :toggle,
      :tooltip
  end
end
