name: CI
concurrency:
  group: '${{github.workflow}}-${{github.ref}}'
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler: latest
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rake rubocop

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4', 'head']
    steps:
      - uses: actions/checkout@v4
      - run: rm Gemfile.lock
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler: latest
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test

  user-install:
    strategy:
      fail-fast: false
      matrix:
        plat: ['ubuntu', 'windows', 'macos']
    runs-on: ${{matrix.plat}}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler: latest
      - run: test/integration/user_install_test.sh
        shell: bash
