name: Github Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  gh_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse Changelog
        id: changelog
        uses: ocavue/changelog-parser-action@v1

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.latestBody }}
